apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  name: custom-v0.1-iso
  namespace: fleet-default
spec:
  metadata:
    displayName: SL Micro 6.0 custom v0.1 ISO x86_64
    uri: registry01.suse/elemental/micro-baremetal-iso:0.1
  type: iso
  version: v0.1
