apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: elemental-1-registration
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: sles
          passwd: suse1234
    elemental:
      install:
        reboot: true
        device: /dev/vda
        debug: true
        # do not define machineName to avoid duplicates and let it generate automatically as m-$UUID
        #  machineName: elemental-1-machine
  machineInventoryLabels:
    location: "europe"
    cluster: "1"
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
