apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: elemental-1-selector-worker
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: cluster
            operator: In
            values: [ '1' ]
          - key: master
            operator: In
            values: [ 'false' ]
