---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rancher-ca-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher.suse
  namespace: cert-manager
spec:
  secretName: rancher-ca
  issuerRef:
    name: rancher-ca-issuer
  commonName: rancher.suse
  isCA: true
  dnsNames:
  - "rancher.suse"
  - "*.rancher.suse"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rancher-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: rancher-ca

