apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-metrics-policy
  namespace: kube-system
spec:
  ingress:
  - from:
    - podSelector: {}
  - ports:
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      app: rke2-metrics-server
  policyTypes:
  - Ingress
