apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-test-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vsphere

