image:
  empty: rancher/pause:3.1
  # elemental-operator image is also build on:
  #   registry.opensuse.org/isv/rancher/elemental/teal53/15.4/rancher/elemental-operator
  repository: "registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-operator/5.3"
  tag: 0.6.3
  imagePullPolicy: IfNotPresent

# number of operator replicas to deploy
replicas: 1

# http[s] proxy server
# proxy: http://<username>@<password>:<url>:<port>

# comma separated list of domains or ip addresses that will not use the proxy
noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

global:
  cattle:
    systemDefaultRegistry: ""

# default sync interval for upgrade channel
sync_interval: "60m"

# namespace the operator will watch for, leave empty for all
sync_namespaces: []

# enable debug output for operator
debug: false

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: cattle.io/os
    operator: "Equal"
    value: "linux"
    effect: NoSchedule

