apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: s3gw-psp-rolebinding
  namespace: s3gw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: s3gw-psp-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: s3gw
