certManager:
  # DaemonSet or Deployment
  kind: DaemonSet
  replicaCount: 1
  # Adds additional labels to pods
  additionalPodLabels: {}
  # label1: test
  # label2: test

  image:
    repository: joeelliott/cert-exporter
    # The default tag is ".Chart.AppVersion", only set "tag" to override that
    tag: 
    pullPolicy: IfNotPresent
    command: ["./app"]
    args:
      #- --secrets-annotation-selector=cert-manager.io/certificate-name
      #- --secrets-include-glob=*.crt
      - --logtostderr
      - --include-cert-glob=/var/lib/rancher/rke2/server/tls/*.crt
      - --include-cert-glob=/var/lib/rancher/rke2/server/tls/etcd/*.crt
      - --include-kubeconfig-glob=/etc/rancher/rke2/rke2.yaml
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  # environment: prod
  # prometheus.io/scrape: true
  # prometheus.io/port: 8080
  # prometheus.io/path: /metrics

  podSecurityContext:
    fsGroup: 10010

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: "true"

  tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists

  affinity: {}

  volumes:
    - name: rke2-tls
      hostPath:
        path: /var/lib/rancher/rke2/server/tls
        type: Directory
    - name: rke2-kubeconfig
      hostPath:
        path: /etc/rancher/rke2
        type: Directory
    # - name: kubelet
    #   hostPath:
    #     path: /var/lib/kubelet
    #     type: Directory
  volumeMounts:
    # - mountPath: /var/lib/kubelet/pki
    #   mountPropagation: HostToContainer
    #   name: kubelet
    #   readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls
      name: rke2-tls
      readOnly: true
    - mountPath: /etc/rancher/rke2
      name: rke2-kubeconfig
      readOnly: true

  containerPort: 8080

service:
  type: ClusterIP
  port: 8080

  portName: http-metrics

  # Annotations to add to the service
  annotations: {}

  # Requires prometheus-operator to be installed
  serviceMonitor:
    create: true

    # cannot be empty
    additionalLabels:
      prometheus.io/load-rule: "true"

    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: 30s

    ## metric relabel configs to apply to samples before ingestion.
    ##
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]

    # relabel configs to apply to samples before ingestion.
    ##
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace

rbac:
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: cert-exporter-ds

  clusterRole:
    # New role to grant to the service account
    create: true
    # Annotations to add to the service account
    annotations: {}
    # Rules for the Role
    rules:
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "list"]

  clusterRoleBinding:
    create: true

dashboards:
  # Labels to add to all dashboard ConfigMaps
  additionalLabels:
    grafana_dashboard: "1"
  certManagerDashboard:
    create: false
  namespace: cert-exporter

