{
 "title": "RKE2",
 "description": "Allows for monitoring RKE2 cluster running Rancher. Uses Prometheus and Loki as data sources.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\".*\"}) / sum(kube_node_status_allocatable_pods{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\".*\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\".*\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Rancher Logs Errors and Warnings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"cattle-system/rancher\"} |~ \"ERROR\" [$__interval]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(count_over_time({job=\"cattle-system/rancher\"} |~ \"WARNING\" [$__interval]))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "API Server Error/Warnings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"kube-system/kube-apiserver\"}[$__interval] |~ \"error\"))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time({job=\"kube-system/kube-apiserver\"}[$__interval] |~ \"warn\"))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Rancher Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"cattle-system/rancher\"}"
    }
   ]
  },
  {
   "title": "API Server Error/Warnings Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"kube-system/kube-apiserver\"} |~ \"error|warn\""
    }
   ]
  },
  {
   "title": "ETCD Warnings and Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"kube-system/etcd\"}[$__interval] |~ \"warn\"))",
     "legendFormat": "Warnings"
    },
    {
     "expr": "sum(count_over_time({job=\"kube-system/etcd\"}[$__interval] |~ \"panic\"))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Controller Manager Errors/Warnings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"kube-system/kube-controller-manager\"}[$__interval] |~ \"error\"))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(count_over_time({job=\"kube-system/kube-controller-manager\"}[$__interval] |~ \"warn\"))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "ETCD Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{job=\"kube-system/etcd\"} |~ \"panic\""
    },
    {
     "expr": "{job=\"kube-system/etcd\"} |~ \"warn\""
    }
   ]
  },
  {
   "title": "Controller Manager Errors/Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "{job=\"kube-system/kube-controller-manager\"} |~ \"error|warn\""
    }
   ]
  }
 ]
}