apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elemental-operator-psp-rolebinding
  namespace: cattle-elemental-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elemental-operator-psp-role
subjects:
- kind: ServiceAccount
  name: elemental-operator
  namespace: cattle-elemental-system
