apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elemental-operator-psp-role
  namespace: cattle-elemental-system
rules:
- apiGroups:
  - policy
  resourceNames:
  - system-unrestricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use

