apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rancher-logging-fluent-psp-binding
  namespace: cattle-logging-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rancher-logging-fluent-psp-role
subjects:
- kind: ServiceAccount
  name: rancher-logging-fluentd
  namespace: cattle-logging-system
- kind: ServiceAccount
  name: rancher-logging-root-fluentd
  namespace: cattle-logging-system
- kind: ServiceAccount
  name: rancher-logging-fluentbit
  namespace: cattle-logging-system
- kind: ServiceAccount
  name: rancher-logging-rke2-containers-fluentd
  namespace: cattle-logging-system
- kind: ServiceAccount
  name: rancher-logging-rke2-journald-fluentd
  namespace: cattle-logging-system

