apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-exporter-psp-role
  namespace: cert-exporter
rules:
- apiGroups:
  - policy
  resourceNames:
  - system-unrestricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-exporter-psp-binding
  namespace: cert-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-exporter-psp-role
subjects:
- kind: ServiceAccount
  name: cert-exporter
  namespace: cert-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-exporter-agent-psp-binding
  namespace: cert-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-exporter-psp-role
subjects:
- kind: ServiceAccount
  name: cert-exporter-agent
  namespace: cert-exporter
