apiVersion: v1
kind: Secret
metadata:
  name: gitrepo-auth-rke-cis-benchmark
  namespace: fleet-local
type: kubernetes.io/basic-auth
data:
  username: cmFuY2hlcg==
  password: a0ttd3llZG5ndzdCeGU4R0Rkd3k=
