apiVersion: v1
kind: Secret
metadata:
  name: gitrepo-auth-rke-cert-exporter
  namespace: fleet-local
type: kubernetes.io/basic-auth
data:
  username: cmFuY2hlcg==
  password: RzdadFd5NmpDQVlIaEFOYVI1dlc=
