{
 "title": "Certificates",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Expiration within 7 days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(cert_exporter_cert_expires_in_seconds <= 604800) OR on() vector(0))+(count(cert_exporter_kubeconfig_expires_in_seconds <= 604800)OR on() vector(0))+(count(cert_exporter_secret_expires_in_seconds <= 604800) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Expiration within 7 and 30 days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(604800 < cert_exporter_cert_expires_in_seconds and cert_exporter_cert_expires_in_seconds <= 2592000)OR on() vector(0))+(count(604800 < cert_exporter_kubeconfig_expires_in_seconds and cert_exporter_kubeconfig_expires_in_seconds <= 2592000)OR on() vector(0))+(count(604800 < cert_exporter_secret_expires_in_seconds and cert_exporter_secret_expires_in_seconds <= 2592000) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Expiration after 30 days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(cert_exporter_cert_expires_in_seconds > 2592000)OR on() vector(0))+(count(cert_exporter_kubeconfig_expires_in_seconds > 2592000)OR on() vector(0))+(count(cert_exporter_secret_expires_in_seconds > 2592000) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Expiration within 7 days Alerts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(cert_exporter_cert_expires_in_seconds <= 604800)OR on() vector(0))+(count(cert_exporter_kubeconfig_expires_in_seconds <= 604800)OR on() vector(0))+(count(cert_exporter_secret_expires_in_seconds <= 604800) OR on() vector(0))",
     "legendFormat": "Expiry in 7 days - count"
    }
   ]
  },
  {
   "title": "Expiration within 30 days Alerts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(604800 < cert_exporter_cert_expires_in_seconds and cert_exporter_cert_expires_in_seconds <= 2592000)OR on() vector(0))+(count(604800 < cert_exporter_kubeconfig_expires_in_seconds and cert_exporter_kubeconfig_expires_in_seconds <= 2592000)OR on() vector(0))+(count(604800 < cert_exporter_secret_expires_in_seconds and cert_exporter_secret_expires_in_seconds <= 2592000) OR on() vector(0))",
     "legendFormat": "Expiry in 30 days - count"
    }
   ]
  },
  {
   "title": "Kubernetes and ETCD PKI Certs Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "cert_exporter_cert_expires_in_seconds"
    }
   ]
  },
  {
   "title": "Kubeconfig Certs Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cert_exporter_kubeconfig_expires_in_seconds"
    }
   ]
  },
  {
   "title": "Secret PKI Certs Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "cert_exporter_secret_expires_in_seconds"
    }
   ]
  }
 ]
}