apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeTAxLnN1c2UiOnsidXNlcm5hbWUiOiJyYW5jaGVyLWNsdXN0ZXIiLCJwYXNzd29yZCI6IjZ0Mm4tTnRSNURlV0NmQ3dCa3JWIiwiYXV0aCI6ImNtRnVZMmhsY2kxamJIVnpkR1Z5T2paME1tNHRUblJTTlVSbFYwTm1RM2RDYTNKVyJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: registry01
type: kubernetes.io/dockerconfigjson
