# required due rancher blocking neuvector setting labels on the cattle-neuvector-system namespace when enabling the neuvector admission webhook - failure just shows up during testing the admission webhook in the neuvector UI..
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-psa
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - projects
  verbs:
  - updatepsa
