# required due rancher blocking neuvector setting labels on the cattle-neuvector-system namespace when enabling the neuvector admission webhook - failure just shows up during testing the admission webhook in the neuvector UI..
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-psa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-psa
subjects:
- kind: ServiceAccount
  name: neuvector
  namespace: cattle-neuvector-system
