defaultNamespace: cert-manager
helm:
  releaseName: cert-manager-config
dependsOn:
  - name: rke-cert-manager-app
targetCustomizations:
- name: local
  yaml:
    overlays:
      - local
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: local
- name: rke-test
  yaml:
    overlays:
      - rke-test
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: rke-test
- name: rke-int
  yaml:
    overlays:
      - rke-int
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: rke-int
- name: rke-prod
  yaml:
    overlays:
      - rke-prod
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: rke-prod

