apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: cert-exporter
  name: cert-exporter
  namespace: cert-exporter
spec:
  selector:
    matchLabels:
      k8s-app: cert-exporter
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        k8s-app: cert-exporter
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/master: "true"
      #tolerations:        
      #- key: node-role.kubernetes.io/master
      #  operator: Exists
      #  effect: NoSchedule
      serviceAccountName: cert-exporter      
      containers:
      - image: joeelliott/cert-exporter:v2.7.0
        name: cert-exporter
        command: ["./app"]
        args:
        - --secrets-include-glob=*.crt
        - --include-cert-glob=/var/lib/rancher/rke2/server/tls/*.crt
        - --include-cert-glob=/var/lib/rancher/rke2/server/tls/etcd/*.crt
        - --include-kubeconfig-glob=/etc/rancher/rke2/rke2.yaml
        - --logtostderr
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts: 
          - mountPath: /var/lib/rancher/rke2/server/tls
            name: rke2-tls
            readOnly: true
          - mountPath: /etc/rancher/rke2
            name: rke2-kubeconfig
            readOnly: true                
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: 500m
            memory: 400M
      volumes: 
        - name: rke2-tls
          hostPath:
            path: /var/lib/rancher/rke2/server/tls
            type: Directory
        - name: rke2-kubeconfig
          hostPath:
            path: /etc/rancher/rke2
            type: Directory
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
       
---
apiVersion: v1
kind: Service
metadata:
  name: cert-exporter-metrics
  namespace: cert-exporter
  labels:
    k8s-app: cert-exporter-metrics
spec:
  selector:
    k8s-app: cert-exporter
  ports:
    - name: metrics
      port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-operator
    prometheus: prometheus-operator-prometheus
    release: prometheus-operator
  name: cert-exporter
  namespace: cert-exporter
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: 20s
  jobLabel: cert-exporter-metrics
  namespaceSelector:
    matchNames:
    - cert-exporter
  selector:
    matchLabels:
      k8s-app: cert-exporter-metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-exporter
  namespace: cert-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-exporter
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-exporter
subjects:
- kind: ServiceAccount
  name: cert-exporter
  namespace: cert-exporter
