apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: rancher-backup-hourly
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 168
  schedule: 0 * * * *
type: resources.cattle.io.backup

