apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-pvc-rwx
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

