---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rke-prod-ca-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rke-prod.suse
  namespace: cert-manager
spec:
  secretName: rke-prod-ca
  issuerRef:
    name: rke-prod-ca-issuer
  commonName: rke-prod.suse
  isCA: true
  dnsNames:
  - "rke-prod.suse"
  - "*.rke-prod.suse"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rke-prod-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: rke-prod-ca

