apiVersion: v1
kind: Secret
metadata:
  name: storageclass-rke-test-default-secret
  namespace: ceph-csi-rbd
type: "kubernetes.io/rbd"
data:
  userID: cmtlLXRlc3QtZGVmYXVsdA== 
  userKey: QVFDUzVuaGlEdmlNRWhBQTFwbC9qYktBN3J1K3YrTDdXVEo4Rmc9PQ==
