apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mimir-distributed-psp-rolebinding
  namespace: mimir
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mimir-distributed-psp-role
subjects:
- kind: ServiceAccount
  name: mimir-distributed
  namespace: mimir
