apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: certificate-alerts
  namespace: cert-exporter
spec:
  groups:
  - name: certificate-alerts
    rules: 
    - alert: Expiration within 7 days alert
      annotations:
        message: "Cluster: \nCritical: certificate will expire in 7 days or less! "
      expr: ((count(cert_exporter_cert_expires_in_seconds <= 604800) + count(cert_exporter_kubeconfig_expires_in_seconds
        <= 604800) + count(cert_exporter_secret_expires_in_seconds <= 604800) or on()
        vector(0)) > 0)
      for: 300s
      labels:
        severity: critical
    - alert: Expiration within 7 and 30 days alert
      annotations:
        message: "Cluster \nMajor: certificate will expire in 30 days or less! "
      expr: ((count(604800 < cert_exporter_cert_expires_in_seconds and cert_exporter_cert_expires_in_seconds
        <= 2.592e+06) + count(604800 < cert_exporter_kubeconfig_expires_in_seconds
        and cert_exporter_kubeconfig_expires_in_seconds <= 2.592e+06) + count(604800
        < cert_exporter_secret_expires_in_seconds and cert_exporter_secret_expires_in_seconds
        <= 2.592e+06) or on() vector(0)) > 0)
      for: 300s
      labels:
        severity: critical
