---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3gw-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4}}
data:
  RGW_BACKEND_STORE: "sfs"
  DEBUG_RGW: "1"
{{- if .Values.ui.enabled }}
  RGW_SERVICE_URL: 'https://{{ .Values.hostname }}'
{{- end }}
  RGW_DEFAULT_USER_SYSTEM: "1"
