---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Chart.Name }}-secret'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
type: Opaque
stringData:
  RGW_DEFAULT_USER_ACCESS_KEY: {{ .Values.accessKey | quote }}
  RGW_DEFAULT_USER_SECRET_KEY: {{ .Values.secretKey | quote }}
{{- if .Values.imageCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Chart.Name }}-image-pull-secret'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "s3gw.imagePullSecret" . }}
{{- end }}
