---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-svc'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
spec:
  selector:
{{ include "s3gw.selectorLabels" . | indent 4 }}
  ports:
    - name: s3
      protocol: TCP
      port: 80
      targetPort: s3
{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-ui-svc'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
spec:
  selector:
{{ include "s3gw-ui.selectorLabels" . | indent 4 }}
  ports:
    - name: webui
      protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}
